matrix:
        include:
                - os: linux
                  dist: trusty
                  install:
                          - ./.travis/linux-ubuntu-trusty.install.sh
                - os: osx
                  osx_image: xcode8.3
                  install:
                          - rvm get stable
                          - ./.travis/macosx-xcode8.3.install.sh
language: C
compiler: gcc

script: make test && sudo make install
